### ISSUE TITLE
Enhancement: function to understand variability in the PCS

### ISSUE THREAD

**Issue by weinbergerlab** [functionaldata/tPACE#25]
Jones and Rice 1989 "Displaying the Important Features of Large Collections of Similar Curves" Jones and Rice 1989 had useful ideas for plotting results from PCAs to understand what is driving the variability in the different PCs. I wrote a simple function to allow plotting of the first 4 principal components (1 by 1) and the variability associated with each. I've found this helpful to understand what is driving the variations in each of the PCs:
 plot_func<-function(fpcaObj, plot.quants){
  #Eigenfunctions
  eigenfunc<-fpcaObj$phi  #Eigenfunction
  xiEst2<-fpcaObj$xiEst     
  est.meanfunc<-fpcaObj$mu  #Mean function
  xi.est2.quantiles<- apply(xiEst2,2, quantile, probs=plot.quants)
  yEst.q<-array(NA, dim=c(length(est.meanfunc),3,ncol(xi.est2.quantiles) ))
  #Just reconstruct based on PCN
  for(pcn in 1:ncol(xi.est2.quantiles) ){
    yEst.q[,,pcn]<- t(xi.est2.quantiles[,pcn] %*%  t(eigenfunc[,pcn]) + t(matrix(rep(est.meanfunc,3), nrow=length(est.meanfunc))) )
  }
  return(yEst.q)
}
quants.pca<-plot_func(fpcaObj,plot.quants=c(0.1,0.5,0.9))
par(mfrow=c(2,2))
for(i in 1:4){
matplot(quants.pca[,,i], type='l', bty='l', col=c('#1b9e77','#d95f02','#7570b3' ), lty=c(2,1,3), lwd=c(1,2,1)) #Plot 1st principal component range
  title(paste0("Variation associated with PCA ", i,"; ", round(pct.var.pca[i],0),"%"))
}
This shows, for instance, that the variability in PC1 is driven by differences in the height of the growth curves, , while PC2 is driven by variability in timing.

![image](https://user-images.githubusercontent.com/24397106/43019951-83cc6b24-8c2c-11e8-8801-e6286dae4dc1.png)

**Comment by hadjipantelis** [comment]
Associated commit done: 2f9313e; will merge in due time.

**Comment by weinbergerlab** [comment]
Ah great thank you! Wasn't clear from the documentation that that is what it was doing.
Best,
Dan

**Comment by weinbergerlab** [comment]
Having an option to plot without shading would be helpful, too.  In some instances the shading makes it harder to interpret the plots (ie compare plot below for PC2 with plot above:
![image](https://user-images.githubusercontent.com/24397106/43081082-30659412-8e5f-11e8-8c56-38190d241791.png)

**Comment by hadjipantelis** [comment]
That documentation needs some extra work... I will look into it, thanks for the feedback.

Regarding what you showed, you can check the option `rainbow = TRUE`. It is a "hybrid" of the first and second plot! That said, I will look into adding a `minimal` option too so it resembles something close to what you showed.

Best,
Pantelis
