### ISSUE TITLE
A question about function kCFC.

### ISSUE THREAD

**Issue by HangjunGong** [functionaldata/tPACE#4]
Hello, I have a question about function kCFC.
It seems kCFC in package fdapace can not choose M_{c} that J.-M. Chiou mentioned in the iterative updating step in his paper.

**Comment by hadjipantelis** [comment]
Hello Hangjun,

The function kCFC() does update M_c with each iteration but does not directly expose this procedure to the user. 

M_c, the number of components used to reconstruct a specific cluster, is chosen adaptively in each iteration for each cluster. This is done by the cluster-specific FPCA decompositions that are recomputed in each iteration (the "listOfFPCAobjs" variable). We currently use a Fraction-of-Variance-Explained (FVE) criterion to pick the optimal number of components, M_c, within each FPCA decomposition as this is analogous to setting the ISE threshold τ_D. One can use different FVE thresholds or different criteria altogether (eg. AIC) by changing the default values of kCFC()'s 'optnsCS' argument.

All the best,
Pantelis
