### ISSUE TITLE
Output grid changed?

### ISSUE THREAD

**Issue by CrossD** [functionaldata/tPACE#50]
https://github.com/functionaldata/tPACE/blob/7721307555707fb4232cb80495a1f4d054354cf9/R/FPCA.R#L41

I was wondering why is the output grid for the covariance function changed in the GitHub version? This may affect many downstream applications since dimension of ``ret$smoothedCov`` changes and may lead to unexpected results. 

Sometimes when I need to make use of the covariance surface on the observation grid, I would just convert them after the FPCA returns. Otherwise, use an additional field ret$smoothCovObs for the obsGrid discretization will also take care of the backward compatibility issue.

**Comment by yqgchen** [comment]
Sorry for the confusion, but that's actually a typo in the documentation part. The default value of userGrid is FALSE.

**Comment by CrossD** [comment]
You are right. Thanks!
