### ISSUE TITLE
How to control the generated fPC scores

### ISSUE THREAD

**Issue by bieyifeng10** [functionaldata/tPACE#53]
Hi there,

Thanks for your time. I have a concern about feature selection.

So I have a dataset of gas spectra, which is a mixture of 9 gases. I used FPCA for dimension reduction and feature extraction. How ever, one gas has a small signal and the code can only generate 8 scores. The prediction for that gas is 50% accuracy cause no information was extracted. 

I find that the FEV threshold is 99% for default, and in my code, the FEV for 8 scores is 100%. I was wondering is there any parameter that I can use to force the code to generate 9 scores, so the gas will small signal will no longer be treated as noise.

I appreciate any suggestion. Thanks!
YB

**Comment by hadjipantelis** [comment]
Thank you for interest in `fdapace`.  Can you please confirm that you are using `FVEthreshold=1.00` as an option such that we use 100% of the  Variance-Explained by the SVD? If yes, can you please try and set the bandwidths used to smooth the mean and covariance functions, to lower values than the one currently used (see the control parameters `userBwMu` and `userBwCov` respectively); using smaller values would allow more variability to be captured.
