### ISSUE TITLE
Numerical instability in GetCEScores.R

### ISSUE THREAD

**Issue by CrossD** [functionaldata/tPACE#57]
`GetMuPhiSig` is numerically unstable because it uses `pracma::approx2`. It fails if two observed time points are too close by within a distance of `1e-8`. Please use `ConvertSupport(..., Cov=..., isCrossCov=...)` instead.

**Comment by aegajardo** [comment]
Thanks, this issue on GetCEScores.R function was addressed in fdapace version 0.5.8.
