### ISSUE TITLE
FLM does not estimate the intercept function correctly

### ISSUE THREAD

**Issue by CrossD** [functionaldata/tPACE#58]
If you read the code, you will find that the mean function of Y is not added back to `alpha`. Specifically, line 286 of `FLM.R` is 

```
    alpha <- c(estEigenY%*%alphaVec)
```

`alphaVec` is simply the intercepts from the regression of mean zero FPC scores of Y on those of the predictors, so it does not contain the mean.

This issue occurs for both the scalar and functional response cases.

**Comment by aegajardo** [comment]
Thanks, this issue in FLM.R function was addressed in fdapace version 0.5.8.
