### ISSUE TITLE
Stringing

### ISSUE THREAD

**Issue by dmchris** [functionaldata/tPACE#6]
Stringing is to be implemented to provide a way of transforming high dimensional multivariate data to functional data. To be released in ver 0.4.0. @dmchris

- References:
> Chen K, Chen K, Müller H G, et al. Stringing high-dimensional data for functional analysis. Journal of the American Statistical Association, 2011, 106(493): 275-284.

**Comment by hadjipantelis** [comment]
Created PR. If Travis is OK with this, this issue should be closed.
