### ISSUE TITLE
Check correlation of FPCA output

### ISSUE THREAD

**Issue by MichaelJStein** [functionaldata/tPACE#61]
Hi,

is it possible to check if the FPCA output is uncorrelated? The eigenfunctions should be orthonormal by definition but I would like to know if there is a function to confirm this. Maybe CreateCovPlot is what I am looking for?

Thank you very much!

Best,
Michael

**Comment by aegajardo** [comment]
Hi,

For sparse designs, the estimated FPC scores are correlated. The estimated eigenfunctions should be orthonormal and this can be checked numerically for example using Riemann sum approximations. The function 'trapzRcpp' in fdapace implements the trapezoidal rule for numerical integration. The 'CreateCovPlot' function displays the estimated covariance or correlation surface of the underlying process.
